### PR TITLE
Release/obsproc.v1.0.0 - final NCO teaks and /trigger changes

### PR DESCRIPTION
**Pull request by ilianagenkova**

### CODE REVIEW

**Comment by ilianagenkova** [comment]
@ShelleyMelchior-NOAA , a few tiny NCO suggested changes are here, and the /trigger changes (with correct order for user developed modules). I will work on the triggers tomorrow, but am opening this PR to remind me.

**Comment by ilianagenkova** [comment]
ps. At some point (next obsproc upgrade) will pass our latest/greatest triggers to NCO ,  to be in sync.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
This all looks good to me. My only recommendation, which doesn't have to hold up this PR necessarily, but is something you should consider, is remove all module business for bufr_dump in any prep or prep_post triggers. 
No dump or dump_post triggers do any prepobs module business. Likewise, no prep or prep_post triggers should include bufr_dump module business.
Having it in there does not hurt anything, but it is extraneous and may cause confusion.

**Comment by ilianagenkova** [comment]
@ShelleyMelchior-NOAA Intend to get it done for all network-centric triggers. Might leave the  non-network triggers as is for now, until I get more familiar with them.

**Comment by ilianagenkova** [comment]
Holding onto the release branch, just for a bit longer. Will delete as soon as I handle Kate's develop-rd. She needs to update it and PR it to us.

**Pull request merged**
