### PR TITLE
Release/obsproc.v1.0.0

### PR DESCRIPTION
**Pull request by ShelleyMelchior-NOAA**
Merging release/obsproc.v1.0.0 into develop. NCO SPA interaction re: port to WCOSS2 has stablized.

### CODE REVIEW

**Comment by aerorahul** [comment]
I will note that the movement of the CMakeLists.txt etc falls squarely flat to universal practices (of a project built with CMake).

**Comment by ShelleyMelchior-NOAA** [comment]
@aerorahul , noted. Please recall this was a requirement imposed by NCO, that you helped us navigate. NCO did not want any top level files.  Instead, CMakeLists.txt now resides in build-obsproc/.

**Comment by aerorahul** [comment]
> @aerorahul , noted. Please recall this was a requirement imposed by NCO, that you helped us navigate. NCO did not want any top level files. Instead, CMakeLists.txt now resides in build-obsproc/.

That is correct.  I helped navigate for this NCO implementation.  I also recall we agreed this will not come back to `develop`.

I would like to see where in the NCO implementation standards does it say, that the top-level directory will have only these X files/directories.

**Comment by ShelleyMelchior-NOAA** [comment]
I don't recall mentioning not merging this back into develop. If it can't be in develop, then obsproc will continue to forever work from release/obsproc.v1.0.0 as its main code and it will be renamed to something like "develop-use-this-one." This seems impractical and a fight not worth waging at this point. We can poke this bear after wcoss2 go-live is behind us.

**Comment by aerorahul** [comment]
> I don't recall mentioning not merging this back into develop. If it can't be in develop, then obsproc will continue to forever work from release/obsproc.v1.0.0 as its main code and it will be renamed to something like "develop-use-this-one." This seems impractical and a fight not worth waging at this point. We can poke this bear after wcoss2 go-live is behind us.

You don't need to hold everything in the other branch.  Just the build part.  The code/scripts/etc can be brought back.
I would like to see the NCO document that says no `CMakeLists.txt` or `cmake` directory at the top of the root directory.

**Comment by aerorahul** [comment]
> > I don't recall mentioning not merging this back into develop. If it can't be in develop, then obsproc will continue to forever work from release/obsproc.v1.0.0 as its main code and it will be renamed to something like "develop-use-this-one." This seems impractical and a fight not worth waging at this point. We can poke this bear after wcoss2 go-live is behind us.
> 
> You don't need to hold everything in the other branch. Just the build part. The code/scripts/etc can be brought back. I would like to see the NCO document that says no `CMakeLists.txt` or `cmake` directory at the top of the root directory.

Here is the link to the NCO implementation standards.
https://www.nco.ncep.noaa.gov/idsb/implementation_standards/ImplementationStandards.v11.0.0.pdf?

**Comment by ilianagenkova** [comment]
@aerorahul, point us to a universal practices summary that is approved for use in EMC (be it an email with dos and don'ts), **and** greenlighted by NCO, so could make changes. We keep getting corrected by EIB and NCO, without being instructed first. 
I don't like the idea of develop and release branches having different structures. I'd rather settle this once and not have to go back to it.

**Comment by aerorahul** [comment]
To be clear, I am not opposed to the majority of changes in this PR.
I am only raising concern over the project level `CMakeLists.txt` and `cmake/` directory.
I also want to be very clear that this is not a problem of the developers making.

**Comment by arunchawla-NOAA** [comment]
Can we create an issue on this ? That we need to address this with NCO. This is standard practice for cmake, and there needs to be a very good reason to not adhere to it

**Comment by ShelleyMelchior-NOAA** [comment]
We can. We already had this meeting w/ Steven Earle, his SPA, EIB, obsproc ... back in January, and settled on the solution you see in release/obsproc.v1.0.0.  I am confused why this is not an OK solution now.  NCO acknowledged it is not standard industry practice, but that NCO would not accept the standard industry practice. Do other groups at EMC use cmake? How do they handle this conundrum?

**Comment by ilianagenkova** [comment]
@arunchawla-NOAA, @StevenEarle-NCO, let's try & resolve this here first, without opening separate issue.

Obsproc needs to know how to finalize /obproc code - with or without files (cmake relatd) in the top level directory. See conversation above. thanks!

**Comment by ilianagenkova** [comment]
@aerorahul  we appreciate your email  and will do the merge without the files in question, until an agreeement ObsProc/EIB/NCP is reached.

**Comment by arunchawla-NOAA** [comment]
All our libraries and ufs-weather-model have a top level CMAKELISTS.txt file

**Comment by StevenEarle-NCO** [comment]
Rahul - table 3 of the implementation standards.
I'll be honest, I work on 80+ projects so I don't have every conversation I've ever had with developers committed to memory, but I'm nearly certain that we already talked about this in great detail and this was the solution we collectively decided on. Why are we rehashing this now?
Arun - libraries have different standards wrapped around them, and ufs-weather-model is not in operations yet... but sounds like a fun conversation to come around that!

**Comment by aerorahul** [comment]
We agreed on the solution to get things moving in the interest of time.  We did not agree on the solution as final.

**Comment by arunchawla-NOAA** [comment]
Steven it is a standard for all community software that is being developed, you will have the same issue with all codes that build with cmake  (ufs-weather-model, ufs-utils, jedi, etc). I do not know the history behind this, but it will probably be a big issue. I am not sure I clearly understand why having this is a problem

**Comment by StevenEarle-NCO** [comment]
I'm having this conversation with Rahul in chat.... here's the process...
Update the implementation standards then build around those standards.
What's happening here is that EMC builds however they want and hopes NCO is going to agree. That's not the way to do business.
I'm happy to update the standards but I'm not going to have whatever EMC wants driven down my throat.

We agreed on the short term solution already; now we can talk about updating the standards in a way that works for both NCO and EMC so you can do future development around those standards.

**Comment by arunchawla-NOAA** [comment]
@StevenEarle-NCO fair enough. I am happy to have an issue as a reminder for EMC and NCO to get together to discuss evolution of standards. EMC is not trying to create new standards but just trying to adhere to standards that have been set up in the larger community. @ShelleyMelchior-NOAA and @ilianagenkova if you want to create an issue on where cmakelists.txt file will be moved pending a change in implementation standards then that is fine with me

**Comment by aerorahul** [comment]
Action item for @StevenEarle-NCO @arunchawla-NOAA @aerorahul is to incorporate in the established standards document the addition of CMake for projects and then develop in that frame.
That works for me.

**Comment by StevenEarle-NCO** [comment]
Works for me; there are industry standards out there that won't and shouldn't make it into our operational suite. The point is to come to agreement on what we should or shouldn't have in our production environment and then develop (or accept community development) that adheres to these standards.

**Comment by ShelleyMelchior-NOAA** [comment]
@StevenEarle-NCO is there a rough timeline for when NCO implementation standards are re-written and published? Looks like prior to Jan 2022, the previous release was April 2019. Should we expect a similar frequency for the next iteration?

**Comment by ilianagenkova** [comment]
Thank you all! 
I'll finish the PR with /obsproc as is, in agreement with [NCO Implementation Standards version 11.0.0 (Jan [19,2022)]](https://www.nco.ncep.noaa.gov/idsb/implementation_standards/), and more specifically:
Screen Shot 2022-04-07 at 2 50 17 PM

**Comment by StevenEarle-NCO** [comment]
@ShelleyMelchior-NOAA We do it on demand when the need arises; It could be monthly, yearly, multi-yearly... just depends on need. The latest was triggered by the move to WCOSS2, of course, but any need for change can trigger an update.
Minor changes are usually sent to bugzilla (yes, we bugzilla ourselves) and then included in a future update; Major updates trigger a new published version.

**Review by ilianagenkova — APPROVED** [review]

**Pull request merged**
