### PR TITLE
Set obsproc_ver=v1.0 and HOMEgfs=$COMROOT/gfs/v16.2

### PR DESCRIPTION
**Pull request by ilianagenkova**
Replaced obsproc_ver value in all triggers
Updated HOMEgfs in jglobal_prep trigger

@AshleyStanfield-NOAA , just look at the differences as a learning exercise in PR review, and approve PR if you think all looks ok.

@ShelleyMelchior-NOAA, this branch is off /develop b/c release has more changes and I instructed the team to work off develop.

### CODE REVIEW

**Review by AshleyStanfield-NOAA — DISMISSED** [review]
Changes look great.

**Comment by ShelleyMelchior-NOAA** [comment]
I might suggest we have two variables. 
One needs to reflect all three digits, when referencing the software installation in $PACKAGEROOT. This could be $obsproc_ver.
One needs to reflect just the first two digits, when referencing data output in $COMROOT.  This could be $obsproc_ver_com.

**Comment by ShelleyMelchior-NOAA** [comment]
or maybe opposite ... 
obsproc_ver can be the 2 digit variable.
obsproc_ver_install can be the 3 digit variable?

I just know there are times when we need to use both, at least in our triggers when we are using the NCO installed code vs a local installation.

**Comment by ilianagenkova** [comment]
I don't object. Could we introduce obsproc_ver_pcg=v1.0.0 (package version)? 
I don't remember if obsproc_ver is used across NCO, linked to Kate's stacks, etc. so we need to coordinate.

**Comment by ilianagenkova** [comment]
Kate points to obsproc_ver in global-workflow's [run.ver](https://github.com/NOAA-EMC/global-workflow/blob/feature/ops-wcoss2/versions/run.ver#L8) file. 
Thus, I proposed we keep obsproc_ver=v1.0 as is.
I prefer we set obsproc_ver_pckg=v1.0.0 so one can be hinted at $PACKAGEROOT

**Comment by ShelleyMelchior-NOAA** [comment]
I like it. Yes, keep obsproc_ver as is. Introduce obsproc_ver_pckg.

**Comment by AshleyStanfield-NOAA** [comment]
Just to confirm, these changes to obsproc version number are only needed for jglobal prep triggers? No others are affected?

**Comment by ilianagenkova** [comment]
@AshleyStanfield-NOAA, obsproc_ver is set in all triggers. 
I already replaced obsproc_ver=v1.0.0 with obsproc_ver=v1.0 throughout them all, so the work is done.
@ShelleyMelchior-NOAA, shall I add obsproc_ver_pckg=v1.0.0 to all triggers as well? Even if it's not needed right now it isn't harming anyone.

**Comment by ShelleyMelchior-NOAA** [comment]
Yes, go ahead and add $obsproc_ver_pckg to the triggers. This will be needed when one wishes to run NCO's installation of HOMEobsproc. The triggers should have that as a baseline option that gets commented out when one wants to point to a local installation of obsproc code.
Make this change and then update the PR.

**Comment by ShelleyMelchior-NOAA** [comment]
So, for example, don't only add $obsproc_ver_pckg to the triggers, but also update each HOMEobsproc definition line that points to $PACKAGEROOT to use $obsproc_ver_pckg. Thanks!

**Comment by ilianagenkova** [comment]
Introduced 3-digit version variable, obsproc_ver_pckg=v1.0.0, and added it to paths using PACKAGEROOT.

**Comment by ShelleyMelchior-NOAA** [comment]
> Just to confirm, these changes to obsproc version number are only needed for jglobal prep triggers? No others are affected?

@AshleyStanfield-NOAA  this impacts all triggers since all could potentially reference the NCO installation of obsproc rather than a local installation of obsproc.

**Review by ShelleyMelchior-NOAA — APPROVED** [review]
Changes for obsproc variables for both obsproc code installation (obsproc_ver_pckg) and obsproc data output in com (obsproc_ver) look as expected and discussed.

**Pull request merged**
