### PR TITLE
Feature/rel.obs.v1.1.0 syndat nam prep

### PR DESCRIPTION
**Pull request by ilianagenkova**
See https://github.com/NOAA-EMC/obsproc/issues/42 for details
Turn SYNDAT off in nam

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
The code changes look as expected. Have they been tested? @ilianagenkova , have you run the JNAM_PREP processing using these code changes and using production dump files?

**Review by ShelleyMelchior-NOAA — COMMENTED** [review]
All changes look as expected, just curious to know if they have been tested.
Output data files will look no different than operations.
Output log files, check for SYNDATA=NO and check that the variables are not set anywhere or attempted to be used anywhere: $COMINtcvital, $COMSPtcvital.

**Comment by ilianagenkova** [comment]
It's next on the list!

**Comment by ShelleyMelchior-NOAA** [comment]
@ilianagenkova  The NAMsyn cron looks good. I only see the output dir. I assume the com dir was produced and the data files matched operations?

**Comment by ilianagenkova** [comment]
Tested -
..
+ 0s:JOBSPROC_NAM_PREP:L279 + export errPREPDATA_limit=4
+ 0s:JOBSPROC_NAM_PREP:L279 + errPREPDATA_limit=4
+ 0s:JOBSPROC_NAM_PREP:L293 + export SYNDATA=NO
+ 0s:JOBSPROC_NAM_PREP:L293 + SYNDATA=NO
..
and prepbufr files generated.

**Comment by ShelleyMelchior-NOAA** [comment]
And no SYNDAT constituent in resultant prepbufr file.
```
$ binv.x
/lfs/h2/emc/stmp/iliana.genkova/CRON/NAMsyn/com/obsproc/v1.0/nam.20220731/nam.t06z.prepbufr.tm01
 
type        messages       subsets         bytes
 
ADPUPA             1             4          6556        4.00
AIRCAR           595         55485       5915196       93.25
AIRCFT           216         21442       2143034       99.27
SATWND            57          7687        556542      134.86
PROFLR            23            99        198246        4.30
VADWND           419           808       3155834        1.93
ADPSFC           147         16769       1443024      114.07
SFCSHP            82         11098        806300      135.34
MSONET          4276        465978      42504258      108.98
GPSIPW             2           285         14928      142.50
RASSDA             4            39         16664        9.75
ASCATW            17          2420        148538      142.35
TOTAL           5839        582114      56909120
```

**Pull request merged**
