### PR TITLE
Fix modulefiles

### PR DESCRIPTION
**Pull request by kgerheiser**
@ShelleyMelchior-NOAA 

Build works on Hera, Orion, WCOSS2.

### CODE REVIEW

**Comment by ShelleyMelchior-NOAA** [comment]
@kgerheiser can you please work from release/rm-prep instead of develop? That one builds for me, but if you see anything else that might need changes, that would be most helpful. develop is a quite a bit removed from where we are right now. Items have not yet been merged back into develop just yet.

**Comment by ShelleyMelchior-NOAA** [comment]
NOTE: the feature/rm-prep branch does not quite adhere to cmake principles. We had to work w/ NCO for this repo b/c NCO did not want any top level files.

**Comment by kgerheiser** [comment]
Sure, I thought those changes were present in develop.

**Comment by kgerheiser** [comment]
@ShelleyMelchior-NOAA this PR should still merged just for the fixes on Hera, Orion, and the modulefiles.

**Comment by ShelleyMelchior-NOAA** [comment]
I will work these changes into feature/rm-prep instead of develop. Both feature/rm-prep, which was branched from release/obsproc.v1.0.0, are very different from develop. Once we are done iterating w/ NCO, we will merge release/obsproc.v1.0.0 back into develop.

**Comment by kgerheiser** [comment]
Ok, I'll close this then. The relevant fixes are in rm-prep except for the module fixes.

**Pull request closed without merging**
